### ISSUE TITLE
demo.sh启动报错，只贴了一部分报错信息

### ISSUE THREAD

**Issue by weodf** [nobodyiam/apollo-build-scripts#32]
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Disable delta property : false
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Single vip registry refresh property : null
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Force full registry fetch : false
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Application is null : false
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Registered Applications size is zero : true
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Application version is -1: true
2019-08-05 09:41:00.222  INFO 12444 --- [           main] com.netflix.discovery.DiscoveryClient    : Getting all instance registry info from the eureka server
2019-08-05 09:41:16.471 ERROR 12444 --- [           main] c.n.d.s.t.d.RedirectingEurekaHttpClient  : Request execution error

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187)
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123)
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27)
	at com.sun.jersey.api.client.Client.handle(Client.java:652)
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplicationsInternal(AbstractJerseyEurekaHttpClient.java:194)
	at com.netflix.discovery.shared.transport.jersey.AbstractJerseyEurekaHttpClient.getApplications(AbstractJerseyEurekaHttpClient.java:165)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)
	at com.netflix.discovery.shared.transport.decorator.MetricsCollectingEurekaHttpClient.execute(MetricsCollectingEurekaHttpClient.java:73)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134)
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator$6.execute(EurekaHttpClientDecorator.java:137)

**Comment by weodf** [comment]
已解决

**Comment by wwcoding** [comment]
楼上老哥 怎么解决的  遇到一样的问题了

**Comment by wwcoding** [comment]
> 已解决
老哥怎么解决的，遇到一样的问题了
