### ISSUE TITLE
阿里云部署apollo-build-scripts，本地访问不了

### ISSUE THREAD

**Issue by Lucas4585** [nobodyiam/apollo-build-scripts#39]
启动本地项目就会报错，如下，... ...是我省略了，之后就会循环报错 Connection refused: connect。
2019-10-05 18:45:01.181  INFO 4088 --- [           main] c.c.f.a.i.DefaultMetaServerProvider      : Located meta services from apollo.meta configuration: http://阿里云公网IP:8080!
2019-10-05 18:45:06.284  WARN 4088 --- [           main] c.c.f.a.i.RemoteConfigRepository         : Load config failed, will retry in 1 SECONDS. appId: app-lucas-weixin, cluster: default, namespaces: application
2019-10-05 18:45:08.286  WARN 4088 --- [           main] c.c.f.a.i.LocalFileConfigRepository      : Sync config from upstream repository class com.ctrip.framework.apollo.internals.RemoteConfigRepository failed, reason: Load Apollo Config failed - appId: app-lucas-weixin, cluster: default, namespace: application, url: http://阿里云私网IP:8080/configs/app-lucas-weixin/default/application?ip=我本机IP [Cause: Could not complete get operation [Cause: connect timed out]]
2019-10-05 18:45:08.318  WARN 4088 --- [ngPollService-1] c.c.f.a.i.RemoteConfigLongPollService    : Long polling failed, will retry in 1 seconds. appId: app-lucas-weixin, cluster: default, namespaces: application, long polling url: http://阿里云私网IP:8080/notifications/v2?cluster=default&appId=app-lucas-weixin&ip=我本机IP&notifications=%5B%7B%22namespaceName%22%3A%22application%22%2C%22notificationId%22%3A-1%7D%5D, reason: Could not complete get operation [Cause: connect timed out]
2019-10-05 18:45:09.288  WARN 4088 --- [           main] c.c.f.a.i.RemoteConfigRepository         : Load config failed, will retry in 1 SECONDS. appId: app-lucas-weixin, cluster: default, namespaces: application
... ...

com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.9.2.jar:1.9.2]
... ...
	
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method) ~[na:1.8.0_91]
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85) ~[na:1.8.0_91]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_91]
... ...

2019-10-05 18:45:37.644  WARN 4088 --- [           main] c.n.d.s.t.d.RetryableEurekaHttpClient    : Request execution failed with message: java.net.ConnectException: Connection refused: connect
2019-10-05 18:45:37.646 ERROR 4088 --- [           main] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_UNKNOWN/windows10.microdone.cn - was unable to refresh its cache! status = Cannot execute request on any known server

com.netflix.discovery.shared.transport.TransportException: Cannot execute request on any known server
	at com.netflix.discovery.shared.transport.decorator.RetryableEurekaHttpClient.execute(RetryableEurekaHttpClient.java:112) ~[eureka-client-1.9.2.jar:1.9.2]
	at com.netflix.discovery.shared.transport.decorator.EurekaHttpClientDecorator.getApplications(EurekaHttpClientDecorator.java:134) ~[eureka-client-1.9.2.jar:1.9.2]
... ...

我是应该吧 -Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port} 这句话加在 demo.sh 文件的哪里？还是需要怎么做？

**Comment by Lucas4585** [comment]
弄好了，加在demo.sh  BASE_JAVA_OPTS="-Denv=dev -Deureka.instance.homePageUrl=http://${指定的IP}:${指定的Port} "  ，之前好像是我忘记重启了
